name: Back-end CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Docker build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build --platform linux/amd64 -t nedio-back .
        docker tag nedio-back rheech22/nedio-back:${GITHUB_SHA::7}
        docker push rheech22/nedio-back:${GITHUB_SHA::7}
    - name: EC2 deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-34-194-105.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull rheech22/nedio-back:${GITHUB_SHA::7}
          docker tag rheech22/nedio-back:${GITHUB_SHA::7} nedio-back
          docker stop back
          docker run -d --rm -e MONGO_URL=${{ secrets.MONGO_URL }} \
            -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            --name back -p 80:4000 nedio-back
            